name: mobile_tokokeluarga
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0              # Untuk request API ke Laravel
  sqflite: ^2.3.0          # Database lokal untuk mode offline
  path: ^1.9.0             # Helper path database lokal
  path_provider: ^2.1.2    # Mengatur lokasi penyimpanan foto
  image_picker: ^1.0.7     # Mengambil foto bon via Kamera
  camera: ^0.11.0+1        # Untuk UI kamera kustom dengan grid
  connectivity_plus: ^7.1.1 # Mendeteksi status internet
  intl: ^0.19.0            # Formatter tanggal & mata uang
  provider: ^6.1.1         # State management (status sync, loading)
  uuid: ^4.3.3             # Generate unique IDs for offline records
  fl_chart: ^0.70.2        # Untuk grafik/chart
  flutter_secure_storage: ^9.0.0 # Simpan token login
  flutter_image_compress: ^2.3.0 # Kompresi gambar client-side
  dropdown_search: ^5.0.6 # Dropdown dengan pencarian untuk supplier

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
